
import java.util.ArrayList;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javax.swing.tree.DefaultMutableTreeNode;
import javax.swing.tree.DefaultTreeModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author mauri
 */
public class Plataforma extends javax.swing.JFrame {
    ArrayList <Carrera> carreras = new ArrayList();

    Plataforma() {
        initComponents();
        
        carreras.add(new Carrera("Finanzas", "Licenciatura", "Lic. A", 10000));
        carreras.add(new Carrera("Derecho", "Licenciatura", "Lic. B", 10000));
        carreras.add(new Carrera("Administración de Empresas", "Licenciatura", "Lic. C", 10000));
        carreras.add(new Carrera("Diseño Gráfico", "Licenciatura", "Lic. D", 10000));
        carreras.add(new Carrera("Mercadotecnia", "Licenciatura", "Lic. E", 10000));
        carreras.add(new Carrera("Sistemas Computacionales", "Ingeniería", "Lic. F", 10000));
        carreras.add(new Carrera("Industrial y de Sistemas", "Ingeniería", "Lic. G", 10000));
        carreras.add(new Carrera("Mecatrónica", "Ingeniería", "Lic. H", 10000));
        carreras.add(new Carrera("Biomédica", "Ingeniería", "Lic. I", 10000));
        carreras.add(new Carrera("Energía", "Ingeniería", "Lic. J", 10000));
        carreras.add(new Carrera("Medicina y Cirugia", "Ciencias de la Salud", "Lic. K", 10000));
        carreras.add(new Carrera("Odontologia", "Ciencias de la Salud", "Lic. L", 10000));
        carreras.add(new Carrera("Nutricion", "Ciencias de la Salud", "Lic. M", 10000));
        carreras.add(new Carrera("Terapia Física y Ocupacional", "Ciencias de la Salud", "Lic. N", 10000));
        
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jd_estudiante = new javax.swing.JDialog();
        jLabel1 = new javax.swing.JLabel();
        tf_nombreestu = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        tf_apellidoestu = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        ff_cuenta = new javax.swing.JFormattedTextField();
        jLabel4 = new javax.swing.JLabel();
        sp_edadestu = new javax.swing.JSpinner();
        jLabel5 = new javax.swing.JLabel();
        rb_m = new javax.swing.JRadioButton();
        rb_f = new javax.swing.JRadioButton();
        jLabel7 = new javax.swing.JLabel();
        cb_carreras = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        jt_estudiantes = new javax.swing.JTree();
        jScrollPane2 = new javax.swing.JScrollPane();
        jl_estudiantes = new javax.swing.JList<>();
        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel3 = new javax.swing.JPanel();
        popup_estudiante = new javax.swing.JPopupMenu();
        jMenuItem4 = new javax.swing.JMenuItem();
        jd_maestros = new javax.swing.JDialog();
        jLabel6 = new javax.swing.JLabel();
        tf_nombremaes = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        tf_apellidomaes = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        sp_edadmaes = new javax.swing.JSpinner();
        jLabel10 = new javax.swing.JLabel();
        sp_salario = new javax.swing.JSpinner();
        popup_arbol = new javax.swing.JPopupMenu();
        ji_modificar = new javax.swing.JMenuItem();
        ji_eliminar = new javax.swing.JMenuItem();
        jd_modestudiante = new javax.swing.JDialog();
        jLabel11 = new javax.swing.JLabel();
        tf_nombreestu1 = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        tf_apellidoestu1 = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        ff_cuenta1 = new javax.swing.JFormattedTextField();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        rb_m1 = new javax.swing.JRadioButton();
        rb_f1 = new javax.swing.JRadioButton();
        sp_edadestu1 = new javax.swing.JSpinner();
        cb_carreras1 = new javax.swing.JComboBox<>();
        jLabel16 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();

        jd_estudiante.setTitle("Estudiantes");

        jLabel1.setText("Nombre");

        jLabel2.setText("Apellido");

        jLabel3.setText("Num. de Cuenta");

        try {
            ff_cuenta.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("########")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        jLabel4.setText("Edad");

        jLabel5.setText("Genero");

        buttonGroup1.add(rb_m);
        rb_m.setSelected(true);
        rb_m.setText("M");

        buttonGroup1.add(rb_f);
        rb_f.setText("F");

        jLabel7.setText("Carrera");

        cb_carreras.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Finanzas", "Derecho", "Administración de Empresas", "Diseño Gráfico", "Mercadotecnia", "Sistemas Computacionales", "Industrial y de Sistemas", "Mecatrónica", "Biomédica", "Energía", "Medicina y Cirugia", "Odontologia", "Nutricion", "Terapia Física y Ocupacional" }));

        jButton1.setText("Agregar");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });

        javax.swing.tree.DefaultMutableTreeNode treeNode1 = new javax.swing.tree.DefaultMutableTreeNode("Carreras");
        jt_estudiantes.setModel(new javax.swing.tree.DefaultTreeModel(treeNode1));
        jt_estudiantes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jt_estudiantesMouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(jt_estudiantes);

        jl_estudiantes.setModel(new DefaultListModel());
        jl_estudiantes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jl_estudiantesMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jl_estudiantes);

        javax.swing.GroupLayout jd_estudianteLayout = new javax.swing.GroupLayout(jd_estudiante.getContentPane());
        jd_estudiante.getContentPane().setLayout(jd_estudianteLayout);
        jd_estudianteLayout.setHorizontalGroup(
            jd_estudianteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_estudianteLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel7)
                .addGap(48, 48, 48)
                .addComponent(cb_carreras, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(137, 137, 137))
            .addGroup(jd_estudianteLayout.createSequentialGroup()
                .addGap(155, 155, 155)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 317, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jd_estudianteLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jd_estudianteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jd_estudianteLayout.createSequentialGroup()
                        .addGroup(jd_estudianteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5))
                        .addGap(23, 23, 23)
                        .addGroup(jd_estudianteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tf_nombreestu)
                            .addComponent(tf_apellidoestu)
                            .addComponent(ff_cuenta)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jd_estudianteLayout.createSequentialGroup()
                                .addComponent(rb_m)
                                .addGap(31, 31, 31)
                                .addGroup(jd_estudianteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(rb_f)
                                    .addComponent(sp_edadestu, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jd_estudianteLayout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 188, Short.MAX_VALUE)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(88, 88, 88))))
        );
        jd_estudianteLayout.setVerticalGroup(
            jd_estudianteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_estudianteLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jd_estudianteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(tf_nombreestu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(7, 7, 7)
                .addGroup(jd_estudianteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(cb_carreras, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jd_estudianteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jd_estudianteLayout.createSequentialGroup()
                        .addGroup(jd_estudianteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tf_apellidoestu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addGap(24, 24, 24)
                        .addGroup(jd_estudianteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(ff_cuenta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(24, 24, 24)
                        .addGroup(jd_estudianteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(sp_edadestu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(22, 22, 22)
                        .addGroup(jd_estudianteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(rb_f)
                            .addComponent(rb_m))
                        .addGap(18, 18, 18)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jd_estudianteLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 259, Short.MAX_VALUE)
                        .addGroup(jd_estudianteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(44, 44, 44))))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jMenuItem4.setText("Agregar al arbol");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        popup_estudiante.add(jMenuItem4);

        jLabel6.setText("Nombre");

        jLabel8.setText("Apellido");

        jLabel9.setText("Edad");

        jLabel10.setText("Salario");

        javax.swing.GroupLayout jd_maestrosLayout = new javax.swing.GroupLayout(jd_maestros.getContentPane());
        jd_maestros.getContentPane().setLayout(jd_maestrosLayout);
        jd_maestrosLayout.setHorizontalGroup(
            jd_maestrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_maestrosLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jd_maestrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jd_maestrosLayout.createSequentialGroup()
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(sp_salario, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jd_maestrosLayout.createSequentialGroup()
                        .addGroup(jd_maestrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9))
                        .addGap(23, 23, 23)
                        .addGroup(jd_maestrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tf_nombremaes)
                            .addComponent(tf_apellidomaes)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jd_maestrosLayout.createSequentialGroup()
                                .addGap(64, 64, 64)
                                .addComponent(sp_edadmaes, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(468, Short.MAX_VALUE))
        );
        jd_maestrosLayout.setVerticalGroup(
            jd_maestrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_maestrosLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jd_maestrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(tf_nombremaes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(jd_maestrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tf_apellidomaes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addGap(24, 24, 24)
                .addGroup(jd_maestrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(sp_salario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(jd_maestrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(sp_edadmaes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(299, Short.MAX_VALUE))
        );

        ji_modificar.setText("Modificar");
        ji_modificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ji_modificarActionPerformed(evt);
            }
        });
        popup_arbol.add(ji_modificar);

        ji_eliminar.setText("Eliminar");
        ji_eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ji_eliminarActionPerformed(evt);
            }
        });
        popup_arbol.add(ji_eliminar);

        jd_modestudiante.setTitle("Modificar");

        jLabel11.setText("Nombre");

        jLabel12.setText("Apellido");

        jLabel13.setText("Num. de Cuenta");

        try {
            ff_cuenta1.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("########")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        jLabel14.setText("Edad");

        jLabel15.setText("Genero");

        buttonGroup2.add(rb_m1);
        rb_m1.setSelected(true);
        rb_m1.setText("M");

        buttonGroup2.add(rb_f1);
        rb_f1.setText("F");

        cb_carreras1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Finanzas", "Derecho", "Administración de Empresas", "Diseño Gráfico", "Mercadotecnia", "Sistemas Computacionales", "Industrial y de Sistemas", "Mecatrónica", "Biomédica", "Energía", "Medicina y Cirugia", "Odontologia", "Nutricion", "Terapia Física y Ocupacional" }));

        jLabel16.setText("Carrera");

        jButton2.setText("Modificar");
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jd_modestudianteLayout = new javax.swing.GroupLayout(jd_modestudiante.getContentPane());
        jd_modestudiante.getContentPane().setLayout(jd_modestudianteLayout);
        jd_modestudianteLayout.setHorizontalGroup(
            jd_modestudianteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jd_modestudianteLayout.createSequentialGroup()
                .addContainerGap(339, Short.MAX_VALUE)
                .addComponent(jLabel16)
                .addGap(50, 50, 50)
                .addComponent(cb_carreras1, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(94, 94, 94))
            .addGroup(jd_modestudianteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jd_modestudianteLayout.createSequentialGroup()
                    .addGap(51, 51, 51)
                    .addGroup(jd_modestudianteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jd_modestudianteLayout.createSequentialGroup()
                            .addGap(132, 132, 132)
                            .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 317, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jd_modestudianteLayout.createSequentialGroup()
                            .addGroup(jd_modestudianteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel13)
                                .addComponent(jLabel14)
                                .addComponent(jLabel15))
                            .addGap(23, 23, 23)
                            .addGroup(jd_modestudianteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(tf_nombreestu1)
                                .addComponent(tf_apellidoestu1)
                                .addComponent(ff_cuenta1)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jd_modestudianteLayout.createSequentialGroup()
                                    .addComponent(rb_m1)
                                    .addGap(31, 31, 31)
                                    .addGroup(jd_modestudianteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(rb_f1)
                                        .addComponent(sp_edadestu1, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                    .addContainerGap(211, Short.MAX_VALUE)))
        );
        jd_modestudianteLayout.setVerticalGroup(
            jd_modestudianteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_modestudianteLayout.createSequentialGroup()
                .addGap(109, 109, 109)
                .addGroup(jd_modestudianteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cb_carreras1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16))
                .addContainerGap(266, Short.MAX_VALUE))
            .addGroup(jd_modestudianteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jd_modestudianteLayout.createSequentialGroup()
                    .addGap(82, 82, 82)
                    .addGroup(jd_modestudianteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel11)
                        .addComponent(tf_nombreestu1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(24, 24, 24)
                    .addGroup(jd_modestudianteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(tf_apellidoestu1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel12))
                    .addGap(24, 24, 24)
                    .addGroup(jd_modestudianteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel13)
                        .addComponent(ff_cuenta1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(24, 24, 24)
                    .addGroup(jd_modestudianteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel14)
                        .addComponent(sp_edadestu1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(22, 22, 22)
                    .addGroup(jd_modestudianteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel15)
                        .addComponent(rb_f1)
                        .addComponent(rb_m1))
                    .addGap(18, 18, 18)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(36, Short.MAX_VALUE)))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jMenu1.setText("Tipos");
        jMenu1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu1ActionPerformed(evt);
            }
        });

        jMenuItem1.setText("Estudiante");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuItem2.setText("Maestro");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuItem3.setText("Clase");
        jMenu1.add(jMenuItem3);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 180, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 310, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenu1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu1ActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jMenu1ActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        jd_estudiante.setModal(true);
        jd_estudiante.pack();
        jd_estudiante.setVisible(true);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        // TODO add your handling code here:
        try{
            String nombre = tf_nombreestu.getText();
            String apellido = tf_apellidoestu.getText();
            String cuenta = ff_cuenta.getText();
            int edad = (Integer)sp_edadestu.getValue();
            String sexo="";
            if (rb_m.isSelected()){
                sexo="Maculino";
            }
            else{
                sexo="Femenino";
            }
            Carrera carrera= new Carrera();
            for (int i = 0; i < 14; i++) {
                for (int j = 0; j < carreras.size(); j++) {
                    if ((String)cb_carreras.getSelectedItem() == carreras.get(j).getNombre()){
                        carrera = carreras.get(j);
                    }
                }
            }
            DefaultListModel modelo = (DefaultListModel) jl_estudiantes.getModel();
            modelo.addElement(new Estudiante(nombre, apellido, sexo, cuenta, edad, carrera));
            jl_estudiantes.setModel(modelo);
            tf_nombreestu.setText("");
            tf_apellidoestu.setText("");
            ff_cuenta.setText("");
            sp_edadestu.setValue(20);
            cb_carreras.setSelectedIndex(0);
        }
        catch (Exception e){
            JOptionPane.showMessageDialog(jd_estudiante, "No se pudo agregar el nuevo alumno ya que uno de los valores es invalido");
        }
    }//GEN-LAST:event_jButton1MouseClicked

    private void jl_estudiantesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jl_estudiantesMouseClicked
        // TODO add your handling code here:
        if (jl_estudiantes.getSelectedIndex() >= 0) {
            if (evt.isMetaDown()) {
                popup_estudiante.show(evt.getComponent(),
                        evt.getX(), evt.getY());

            }
        }
    }//GEN-LAST:event_jl_estudiantesMouseClicked

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        // TODO add your handling code here:
        DefaultTreeModel modeloARBOL = (DefaultTreeModel) jt_estudiantes.getModel();
        DefaultMutableTreeNode raiz = (DefaultMutableTreeNode) modeloARBOL.getRoot();
        DefaultListModel modeloLISTA = (DefaultListModel) jl_estudiantes.getModel();
        Estudiante estudiante = (Estudiante) modeloLISTA.get(jl_estudiantes.getSelectedIndex());
        int c = -1;
        for (int i = 0; i < raiz.getChildCount(); i++) {
            if (raiz.getChildAt(i).toString(). equals(estudiante.getCarrera().getNombre())) {
                DefaultMutableTreeNode p = new DefaultMutableTreeNode(estudiante);
                ((DefaultMutableTreeNode) raiz.getChildAt(i)).add(p);
                c = 1;
            } //fin if
        } //fin for
        if (c == -1) {
            DefaultMutableTreeNode n
                    = new DefaultMutableTreeNode(estudiante.getCarrera().getNombre());
            DefaultMutableTreeNode p
                    = new DefaultMutableTreeNode(estudiante);
            n.add(p);
            raiz.add(n);
        }  // fin if   
        modeloARBOL.reload();

    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jt_estudiantesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jt_estudiantesMouseClicked
        // TODO add your handling code here:
        if (evt.isMetaDown()) {
            //seleccionar un nodo con click derecho
            int row = jt_estudiantes.getClosestRowForLocation(
                    evt.getX(), evt.getY());
            jt_estudiantes.setSelectionRow(row);
            Object v1
                    = jt_estudiantes.getSelectionPath().
                    getLastPathComponent();
            nodo_seleccionado = (DefaultMutableTreeNode) v1;
            if (nodo_seleccionado.getUserObject() instanceof Estudiante) {
                estudiante_seleccionado
                        = (Estudiante) nodo_seleccionado.
                        getUserObject();
                popup_arbol.show(evt.getComponent(),
                        evt.getX(), evt.getY());
            }
            

        }
    }//GEN-LAST:event_jt_estudiantesMouseClicked

    private void ji_eliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ji_eliminarActionPerformed
        // TODO add your handling code here:
        DefaultTreeModel m = (DefaultTreeModel) jt_estudiantes.getModel();
            m.removeNodeFromParent(nodo_seleccionado);
            m.reload();
    }//GEN-LAST:event_ji_eliminarActionPerformed

    private void ji_modificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ji_modificarActionPerformed
        // TODO add your handling code here:
        Estudiante estudiante = (Estudiante) nodo_seleccionado.getUserObject();
            tf_nombreestu1.setText(estudiante.getNombre());
            tf_apellidoestu1.setText(estudiante.getApellido());
            ff_cuenta1.setText(estudiante.getCuenta());
            sp_edadestu1.setValue(estudiante.getEdad());
        jd_modestudiante.setModal(true);
        jd_modestudiante.pack();
        jd_modestudiante.setVisible(true);
            
    }//GEN-LAST:event_ji_modificarActionPerformed

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
        // TODO add your handling code here:
        try{
            
            String nombre = tf_nombreestu1.getText();
            String apellido = tf_apellidoestu1.getText();
            String cuenta = ff_cuenta1.getText();
            int edad = (Integer)sp_edadestu1.getValue();
            String sexo="";
            if (rb_m1.isSelected()){
                sexo="Maculino";
            }
            else{
                sexo="Femenino";
            }
            Carrera carrera= new Carrera();
            for (int i = 0; i < 14; i++) {
                for (int j = 0; j < carreras.size(); j++) {
                    if ((String)cb_carreras1.getSelectedItem() == carreras.get(j).getNombre()){
                        carrera = carreras.get(j);
                    }
                }
            }
            DefaultTreeModel m = (DefaultTreeModel) jt_estudiantes.getModel();
            estudiante_seleccionado = new Estudiante(nombre, apellido, sexo, cuenta, edad, carrera);
            m.reload();
            JOptionPane.showMessageDialog(jd_modestudiante, "Modificacion exitosa");
            jd_modestudiante.setVisible(false);
            tf_nombreestu1.setText("");
            tf_apellidoestu1.setText("");
            ff_cuenta1.setText("");
            sp_edadestu1.setValue(20);
            cb_carreras1.setSelectedIndex(0);
        }
        catch (Exception e){
            JOptionPane.showMessageDialog(jd_estudiante, "No se pudo agregar el nuevo alumno ya que uno de los valores es invalido");
        }
    }//GEN-LAST:event_jButton2MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Plataforma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Plataforma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Plataforma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Plataforma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Plataforma().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JComboBox<String> cb_carreras;
    private javax.swing.JComboBox<String> cb_carreras1;
    private javax.swing.JFormattedTextField ff_cuenta;
    private javax.swing.JFormattedTextField ff_cuenta1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JDialog jd_estudiante;
    private javax.swing.JDialog jd_maestros;
    private javax.swing.JDialog jd_modestudiante;
    private javax.swing.JMenuItem ji_eliminar;
    private javax.swing.JMenuItem ji_modificar;
    private javax.swing.JList<String> jl_estudiantes;
    private javax.swing.JTree jt_estudiantes;
    private javax.swing.JPopupMenu popup_arbol;
    private javax.swing.JPopupMenu popup_estudiante;
    private javax.swing.JRadioButton rb_f;
    private javax.swing.JRadioButton rb_f1;
    private javax.swing.JRadioButton rb_m;
    private javax.swing.JRadioButton rb_m1;
    private javax.swing.JSpinner sp_edadestu;
    private javax.swing.JSpinner sp_edadestu1;
    private javax.swing.JSpinner sp_edadmaes;
    private javax.swing.JSpinner sp_salario;
    private javax.swing.JTextField tf_apellidoestu;
    private javax.swing.JTextField tf_apellidoestu1;
    private javax.swing.JTextField tf_apellidomaes;
    private javax.swing.JTextField tf_nombreestu;
    private javax.swing.JTextField tf_nombreestu1;
    private javax.swing.JTextField tf_nombremaes;
    // End of variables declaration//GEN-END:variables

ArrayList <Maestro> maestros = new ArrayList();
ArrayList <Clase> clases = new ArrayList();
DefaultMutableTreeNode nodo_seleccionado;
Estudiante estudiante_seleccionado;
}
